# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  url: <%= ENV["DATABASE_URL"] %>
  # encoding: utf8
  # adapter: postgresql
  # port: 5432
  # username: <%= ENV["DB_USERNAME"] %>
  # host: <%= ENV["DB_HOST"] %>
  # database: <%= ENV["DB_DATABASE"] %>
  # password: <%= ENV["DB_PASSWORD"] %>
